settings:
  root_dir: "./datasets/places365_10classes"
  checkpoint_path: "/content/drive/MyDrive/weights/Places365 Inpainting/phase 3"
  sample_folder: "/content/drive/MyDrive/results/Places365 Inpainting/phase 3"

  cuda: True
  lr: 0.0001
  batch_size: 8
  num_workers: 4

  step_iters: [50000, 75000, 100000]
  gamma: 0.1

  d_num_layers: 3

  visualize_per_iter: 500
  save_per_iter: 500
  print_per_iter: 10
  num_epochs: 100

  lambda_G: 0.3
  lambda_rec_1: 10.0
  lambda_rec_2: 10.0
  lambda_per: 1.0

  img_size: 256
  max_angle: 4
  max_len: 50
  max_width: 30
  times: 15
